// Per-message provenance chip: the git commit SHA the answer was generated with.
export function HashBadge({ codeSha }: { codeSha?: string | null }) {
  if (!codeSha) return null;
  const short = codeSha === "dev" ? "dev" : codeSha.slice(0, 7);
  return (
    <a
      href={`https://github.com/505labs/confidential-chat/commit/${codeSha}`}
      target="_blank"
      rel="noreferrer"
      title={`Generated by code @ ${codeSha}`}
      className="ml-2 inline-flex items-center gap-1 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-0.5 align-middle font-mono text-[10px] text-emerald-300 hover:bg-emerald-500/20"
    >
      <span className="opacity-70">code</span> {short}
    </a>
  );
}
